#:schema ./.aviutl2-cli/aviutl2.schema.json

[project]
id = "sevenc-nanashi.keyframes-aux2"
name = "keyframes.aux2"
version = "0.1.0"

[artifacts.keyframes-aux2]
destination = "Plugin/keyframes.aux2"

[artifacts.keyframes-aux2.profiles.debug]
source = "target/debug/keyframes_aux2.dll"
build = "cargo build"

[artifacts.keyframes-aux2.profiles.release]
source = "target/release/keyframes_aux2.dll"
build = "cargo build --release"

[artifacts.keyframes-aux2-tra2]
destination = "Script/keyframes.aux2.tra2"
source = "build/keyframes.aux2.tra2"
build = "aulua build"

[development]
aviutl2_version = "latest"
catalog_dependencies = ["KuroNeko.CopyAlias"]
