[plugins]
cargo-prebuilt = "https://github.com/sevenc-nanashi/mise-cargo-prebuilt"

[tools]
"github:karoterra/aviutl2-aulua" = "latest"
"github:sevenc-nanashi/aviutl2-cli" = "0.9.0-preview.0"
"github:EmbarkStudios/cargo-about" = { version = "latest" }
"cargo-prebuilt:cargo-edit" = "latest"
